# Bài tập về nhà Decision Tree, Random Forest


- Thực hiện các yêu cầu dưới đây với tập dữ liệu Australian credit
- Down dữ liệu tại đường link dưới đây và đặt vào folder /data
 
  https://archive.ics.uci.edu/ml/datasets/Statlog+(Australian+Credit+Approval)
    

In [13]:
# import packages,...
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
import math
from sklearn.model_selection import train_test_split


# set random_state = 0


## 1. Tìm hiểu dữ liệu

In [14]:
'''
- Tìm hiểu cấu trúc data tại trang web UCI
- Down các files, đặt trong folder data/
- Chú ý:
    - Đọc mô tả dữ liệu trong file 'australian.doc'
    - Kiểm tra DecisionTree/RandomForest của Sklearn có hỗ trợ với kiểu dữ liệu được cung cấp không
'''
data_path = 'australian.dat'

columns = [f'A{i}' for i in range(1, 16)]
df = pd.read_csv(data_path, delim_whitespace=True, header=None, names=columns)
df.head()


C:\Users\phan\AppData\Local\Temp\ipykernel_17856\335736576.py:11: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(data_path, delim_whitespace=True, header=None, names=columns)


A1     A2     A3  A4  A5  A6     A7  A8  A9  A10  A11  A12  A13   A14  A15
0   1  22.08  11.46   2   4   4  1.585   0   0    0    1    2  100  1213    0
1   0  22.67   7.00   2   8   4  0.165   0   0    0    0    2  160     1    0
2   0  29.58   1.75   1   4   4  1.250   0   0    0    1    2  280     1    0
3   0  21.67  11.50   1   5   3  0.000   1   1   11    1    2    0     1    1
4   1  20.17   8.17   2   6   4  1.960   1   1   14    0    2   60   159    1

## 2. Decision Tree

### 2.1. Khảo sát các giá trị khác nhau của max_depth

In [36]:
# code
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
list_max_depth = [1, 3, 5, 10, 12, 15, 20]
X = df.iloc[:, :-1]  
y = df.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size = 0.3)
for i in list_max_depth:   
    des_tree = DecisionTreeClassifier(max_depth = i)
    des_tree.fit(X_train, y_train)
    y_pred = des_tree.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)
    print(cm)

[[102  24]
 [  7  74]]
[[99 27]
 [ 5 76]]
[[106  20]
 [ 12  69]]
[[113  13]
 [ 17  64]]
[[110  16]
 [ 19  62]]
[[112  14]
 [ 18  63]]
[[111  15]
 [ 18  63]]


### 2.2. Tìm kiếm siêu tham số

In [29]:
#code
from sklearn.model_selection import GridSearchCV
param_list= {
    'max_depth': [1, 3, 5, 10, 12, 15, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 5]
}
hyper_search = GridSearchCV(des_tree, param_list, cv=5, scoring='accuracy',  n_jobs=-1)
hyper_search.fit(X_train, y_train)
best_param = hyper_search.best_params_
print(f"Best Parameters: {best_param}")


c:\Users\phan\miniconda3\Lib\site-packages\numpy\ma\core.py:2881: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


Best Parameters: {'max_depth': 1, 'min_samples_leaf': 1, 'min_samples_split': 2}


## 3. Random Forest

### 3.1 Khảo sát các giá trị khác nhau của n_estimators

In [37]:
#code
from sklearn.ensemble import RandomForestClassifier
list_n_estimators = [1, 2, 5, 10, 20, 50, 100, 200, 500]
for i in list_n_estimators:   
    rf = RandomForestClassifier(n_estimators = i)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)
    cm2 = confusion_matrix(y_test, y_pred)
    print(cm2)


[[105  21]
 [ 24  57]]
[[115  11]
 [ 25  56]]
[[113  13]
 [ 17  64]]
[[115  11]
 [ 14  67]]
[[117   9]
 [ 19  62]]
[[114  12]
 [ 17  64]]
[[115  11]
 [ 16  65]]
[[115  11]
 [ 16  65]]
[[114  12]
 [ 14  67]]


### 3.2 Tìm kiếm siêu tham số

In [43]:
# code
param_list= {
    
    'n_estimators': [1, 2, 5, 10, 20, 50],  
    'max_depth': [10, 20, 30],      
    'min_samples_split': [2, 5, 8],      
    'min_samples_leaf': [1, 2, 3],        
    'bootstrap': [True, False]
}
hyper2_search = GridSearchCV(estimator=rf, param_grid=param_list, cv=5, scoring='accuracy', n_jobs=-1, verbose=2)
hyper2_search.fit(X_train, y_train)
best_param = hyper2_search.best_params_
print(f"Best Parameters: {best_param}")


Fitting 5 folds for each of 324 candidates, totalling 1620 fits
Best Parameters: {'bootstrap': False, 'max_depth': 20, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 20}
